# Matrix multiplication

In [1]:
a = [[1,4,6],
     [3,2,4]]

b = [[1,4],
     [3,2],
     [1,6]]

# We create a cero matrix C

c= [[0 for j in range(len(b[0]))] for i in range(len(a))]

# We fill matrix c with the sum of the entries of alpha and matrix a
for i in range(len(a)):
    for j in range(len(b[0])):
        element_i=0
        for k in range(len(b)):
            element_i += a[i][k] * b[k][j]
        c[i][j] = element_i

print(c)

[[19, 48], [13, 40]]


In [3]:
# Using the dot product
import numpy as np

a = np.array(a)
b = np.array(b)

c= np.array([[0 for j in range(len(b[0]))] for i in range(len(a))])


for i in range(len(a)):
    for j in range(len(b[0])):
        c[i,j]=np.dot(a[i], b[:,j])
        
print(c)

[[19 48]
 [13 40]]


In [4]:
# A function

import numpy as np

def matrix_mult(A,B):
    c= np.array([[0 for j in range(len(b[0]))] for i in range(len(a))])
    for i in range(len(A)):
        for j in range(len(B[0])):
            c[i,j]=np.dot(A[i], B[:,j])
    return c

matrix_mult(a,b)

array([[19, 48],
       [13, 40]])

In [5]:
# A function using numpy

def matrix_mult(A,B):
    return np.matmul(A,B)

matrix_mult(a,b)

array([[19, 48],
       [13, 40]])