## 3.1 Spaces of vectors

In [1]:
import numpy as np

##### Example 4

In [2]:
A = np.matrix([[1,0],[4,3],[2,3]])

In [3]:
x = np.array([0.4,0.3])

In [4]:
np.matmul(A,x)

matrix([[0.4, 2.5, 1.7]])

In [5]:
x[0]*A[:,0]+x[1]*A[:,1]

matrix([[0.4],
        [2.5],
        [1.7]])

## 3.2 The nullspace of A

##### Example 1

In [6]:
# This method returns a list of vector that span the null space of the matrix A

from sympy import Matrix
A = [[1,2], [3,6]]
A = Matrix(A)

A.nullspace()

[Matrix([
 [-2],
 [ 1]])]

In [7]:
# This method constructs an orthonormal basis for the null space of A using SVD
from scipy.linalg import null_space

A = [[1,2], [3,6]]

ns = null_space(A)
ns

array([[-0.89442719],
       [ 0.4472136 ]])

In [8]:
# Its multiplication gives cero

np.matmul(A, ns)

array([[0.],
       [0.]])

##### Example 3

In [9]:
A = Matrix([[1,2],[3,8]])
A

Matrix([
[1, 2],
[3, 8]])

In [10]:
B = np.vstack((A,A))
B

array([[1, 2],
       [3, 8],
       [1, 2],
       [3, 8]], dtype=object)

In [11]:
C = np.hstack((A,2*A))
C

array([[1, 2, 2, 4],
       [3, 8, 6, 16]], dtype=object)

In [12]:
A.nullspace()

[]

In [13]:
B =Matrix(B)
B.nullspace()

[]

In [14]:
C = Matrix(C)
s1, s2 = C.nullspace()
s1, s2

(Matrix([
 [-2],
 [ 0],
 [ 1],
 [ 0]]),
 Matrix([
 [ 0],
 [-2],
 [ 0],
 [ 1]]))

In [15]:
# s1, s2 are in the null space

np.matmul(C,s1), np.matmul(C,s2)

(array([[0],
        [0]], dtype=object),
 array([[0],
        [0]], dtype=object))

In [16]:
C.rref() # The reduced row echelon form

(Matrix([
 [1, 0, 2, 0],
 [0, 1, 0, 2]]),
 (0, 1))

###### Matrix rank

In [17]:
A = Matrix([[1,1,2,4],[1,2,2,5],[1,3,2,6]])

In [18]:
A.rref()

(Matrix([
 [1, 0, 2, 3],
 [0, 1, 0, 1],
 [0, 0, 0, 0]]),
 (0, 1))

In [19]:
# The rank of the matrix

from numpy.linalg import matrix_rank
A = np.array([[1,1,2,4],[1,2,2,5],[1,3,2,6]])

np.linalg.matrix_rank(A)

2

###### Rank one

In [20]:
A = np.array([[1,3,10],[2,6,20],[3,9,30]])
A

array([[ 1,  3, 10],
       [ 2,  6, 20],
       [ 3,  9, 30]])

In [21]:
A_rref = Matrix(A).rref()
A_rref

(Matrix([
 [1, 3, 10],
 [0, 0,  0],
 [0, 0,  0]]),
 (0,))

In [22]:
np.outer(A[:,0],np.array([1,3,10]))

array([[ 1,  3, 10],
       [ 2,  6, 20],
       [ 3,  9, 30]])

In [23]:
np.linalg.matrix_rank(np.array([[1,3,4],[2,6,8]]))

1

In [24]:
np.linalg.matrix_rank(np.array([[0,3],[0,5]]))

1

In [25]:
np.linalg.matrix_rank(np.array([[5],[2]]))

1

In [26]:
np.linalg.matrix_rank(np.array([[6]]))

1

## 3.3 The complete solution to Ax = b

In [27]:
A = np.array([[1,3,0,2],[0,0,1,4],[1,3,1,6]])
A

array([[1, 3, 0, 2],
       [0, 0, 1, 4],
       [1, 3, 1, 6]])

In [28]:
b = np.array([[1,6,7]])

In [29]:
A_aug = np.hstack((A, b.T))
A_aug

array([[1, 3, 0, 2, 1],
       [0, 0, 1, 4, 6],
       [1, 3, 1, 6, 7]])

In [30]:
Matrix(A_aug).rref()

(Matrix([
 [1, 3, 0, 2, 1],
 [0, 0, 1, 4, 6],
 [0, 0, 0, 0, 0]]),
 (0, 2))

###### One particular solution

In [31]:
x_p = np.array([1,0,6,0])

In [32]:
np.matmul(A,x_p), np.matmul(A,x_p) == b

(array([1, 6, 7]), array([[ True,  True,  True]]))

In [33]:
ns1, ns2=Matrix(A).nullspace()  # The nullspace
ns1, ns2

(Matrix([
 [-3],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [-2],
 [ 0],
 [-4],
 [ 1]]))

##### Example 1

In [34]:
A = Matrix([[1,1],[1,2],[-2,-3]])
A

Matrix([
[ 1,  1],
[ 1,  2],
[-2, -3]])

In [35]:
A.rref()

(Matrix([
 [1, 0],
 [0, 1],
 [0, 0]]),
 (0, 1))

In [36]:
A.nullspace() 

[]

###### The complete solution

In [37]:
A = np.array([[1,1,1],[1,2,-1]])
A

array([[ 1,  1,  1],
       [ 1,  2, -1]])

In [38]:
b = np.array([[3,4]])

In [39]:
A_aug = np.hstack((A,b.T))
A_aug

array([[ 1,  1,  1,  3],
       [ 1,  2, -1,  4]])

In [40]:
Matrix(A_aug).rref()

(Matrix([
 [1, 0,  3, 2],
 [0, 1, -2, 1]]),
 (0, 1))

In [41]:
np.linalg.matrix_rank(A)

2