## 4.1 Orthogonality of the four subspaces

In [60]:
import numpy as np

In [61]:
v = np.array([1,0])
w = np.array([0,1])

In [62]:
np.dot(v,w)

0

In [63]:
np.linalg.norm(v)**2 + np.linalg.norm(w)**2

2.0

In [64]:
np.linalg.norm(v+w)**2

2.0000000000000004

###### Example 3

In [65]:
A = np.array([[1,3,4],[5,2,7]])
x = np.array([1,1,-1]) 

In [66]:
np.matmul(A,x)

array([0, 0])

In [67]:
np.matmul(A[0,:],x)  # Orthogonal

0

In [68]:
np.matmul(A[1,:],x)  # Orthogonal

0

###### Example 4

In [69]:
from sympy import Matrix

In [70]:
B = Matrix([[1,2,3,4,5],[1,2,4,5,6],[1,2,4,5,6]])
B

Matrix([
[1, 2, 3, 4, 5],
[1, 2, 4, 5, 6],
[1, 2, 4, 5, 6]])

In [71]:
B.rref()

(Matrix([
 [1, 2, 0, 1, 2],
 [0, 0, 1, 1, 1],
 [0, 0, 0, 0, 0]]),
 (0, 2))

## 4.2 Projections

In [72]:
P_1 = np.zeros((3,3))  # Proyection onto a line
P_1[2,2] =1
P_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [73]:
P_2 = np.zeros((3,3))   # Proyection onto a plane
P_2[0,0]=1;P_2[1,1]=1
P_2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [74]:
b = np.array([2,3,4])

In [75]:
np.matmul(P_1,b), np.matmul(P_2,b)  

(array([0., 0., 4.]), array([2., 3., 0.]))

In [76]:
np.dot(np.matmul(P_1,b), np.matmul(P_2,b))  # Perpenticular proyections

0.0

In [77]:
np.matmul(P_1,b) + np.matmul(P_2,b)   == b  #The proyections add to b

array([ True,  True,  True])

###### Proyections onto a line

Example 1

In [78]:
b = np.array([1,1,1])
a = np.array([1,2,2])
vp = (np.dot(a, b) / np.linalg.norm(a)**2 ) * a
print(vp)

[0.55555556 1.11111111 1.11111111]


In [79]:
e = b-vp
e

array([ 0.44444444, -0.11111111, -0.11111111])

In [80]:
np.dot(a,e).round(0)   # a is orthogonal to e

-0.0

In [81]:
P = (np.outer(a,a))/np.dot(a,a)
P

array([[0.11111111, 0.22222222, 0.22222222],
       [0.22222222, 0.44444444, 0.44444444],
       [0.22222222, 0.44444444, 0.44444444]])

In [82]:
np.matmul(P,a)

array([1., 2., 2.])

###### Example 2

In [83]:
a = np.array([1,2,2])

In [84]:
P = (np.outer(a,a))/np.inner(a,a)
P

array([[0.11111111, 0.22222222, 0.22222222],
       [0.22222222, 0.44444444, 0.44444444],
       [0.22222222, 0.44444444, 0.44444444]])

In [85]:
b = np.array([1,1,1])

In [86]:
np.matmul(P,b)

array([0.55555556, 1.11111111, 1.11111111])

In [87]:
e = b - np.matmul(P,b)
e

array([ 0.44444444, -0.11111111, -0.11111111])

In [88]:
np.dot(e,np.matmul(P,b)).round(1)  # The proyection matrix and b are perpendicular

-0.0

In [89]:
np.dot(e,a).round(0)  # a and b are perpendicular

-0.0

###### Proyections onto a line

###### Example 3

In [90]:
A = np.array([[1,0],[1,1],[1,2]])

In [91]:
b = np.array([6,0,0])

In [92]:
np.matmul(A.T,A) # A transpose times A

array([[3, 3],
       [3, 5]])

In [93]:
np.matmul(A.T,b) # A transpose times b

array([6, 0])

In [94]:
x = np.linalg.solve(np.matmul(A.T,A),np.matmul(A.T,b))
x

array([ 5., -3.])

In [95]:
p = np.matmul(A,x)  # The projection
p

array([ 5.,  2., -1.])

In [96]:
e = b - p
e

array([ 1., -2.,  1.])

In [97]:
np.matmul(A.T,e)   # The column space is perpendicular to e

array([0., 0.])

In [98]:
P = np.matmul(A,np.matmul(np.linalg.inv(np.matmul(A.T,A)),A.T))
P

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [99]:
np.matmul(P,b)  

array([ 5.,  2., -1.])

## 4.3 Least squares approximations

##### Example 1

In [100]:
A = np.array([[1,0],[1,1],[1,2]])
A

array([[1, 0],
       [1, 1],
       [1, 2]])

In [101]:
b = np.array([6,0,0])
b

array([6, 0, 0])

In [102]:
np.linalg.inv(A.T @ A) @ A.T @ b

array([ 5., -3.])

## 4.4 Orthonormal bases and Gram-Schmidt

###### Rotation

In [103]:
theta = np.radians(30)
c, s = np.cos(theta), np.sin(theta)
rotation_matrix = np.array([[c,-s],[s,c]])

In [104]:
rotation_matrix

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [105]:
np.matmul(rotation_matrix.T,rotation_matrix).round(1)  

array([[1., 0.],
       [0., 1.]])

###### Reflection

In [106]:
u = np.array([-1/np.sqrt(2),1/np.sqrt(2)])
u

array([-0.70710678,  0.70710678])

In [107]:
(np.identity(2)-2*np.outer(u,u)).round(1)

array([[0., 1.],
       [1., 0.]])

###### Example 4

In [108]:
q = 1/3 *Matrix([[-1,2,2],[2,-1,2],[2,2,-1]])
q

Matrix([
[-0.333333333333333,  0.666666666666667,  0.666666666666667],
[ 0.666666666666667, -0.333333333333333,  0.666666666666667],
[ 0.666666666666667,  0.666666666666667, -0.333333333333333]])

In [109]:
np.matmul(q,q.T)  == np.matmul(q.T,q)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [110]:
# The proyection of b onto q

b = np.array([0,0,1])
q @ (q.T @ b)

array([0, 0, 1.00000000000000], dtype=object)

In [111]:
q @ (q.T @ b)  == b

array([ True,  True,  True])

###### The Gram-Schmidt process

In [112]:
a = np.array([1,-1,0])
b = np.array([2,0,-2])
c = np.array([3,-3,3])

In [113]:
a

array([ 1, -1,  0])

In [114]:
a @ a

2

In [115]:
a @ b

2

In [116]:
X = np.vstack((a,b,c))
X

array([[ 1, -1,  0],
       [ 2,  0, -2],
       [ 3, -3,  3]])