## 5.1 The properties of determinants

In [1]:
import numpy as np

In [2]:
I = np.identity(2)
I

array([[1., 0.],
       [0., 1.]])

In [3]:
np.linalg.det(I)

1.0

In [4]:
P = np.array([[0,1],[1,0]]) @ I
P

array([[0., 1.],
       [1., 0.]])

In [5]:
np.linalg.det(P)

-1.0

##### Linearity does not mean det(A+B) = det(A)+det(B)

In [6]:
A, B = np.identity(2),np.identity(2)

In [7]:
np.linalg.det(A+B),np.linalg.det(A)+np.linalg.det(A)

(4.0, 2.0)

###### 1. The determinant of the I matrix is 1

In [8]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.linalg.det(I)

1.0

###### 2. The determinant changes sign with row exchange

In [10]:
P = np.array([[0,1,0],[1,0,0],[0,0,1]])

In [11]:
Per = P @ I
np.linalg.det(Per)

-1.0

###### 3. The determinant changes sign with row exchange

In [12]:
A = np.array([[1,2,2],[0,1,1],[0,0,1]])
A

array([[1, 2, 2],
       [0, 1, 1],
       [0, 0, 1]])

In [13]:
4*np.linalg.det(A)

4.0

In [14]:
A[0,:]*=4

In [15]:
A

array([[4, 8, 8],
       [0, 1, 1],
       [0, 0, 1]])

In [16]:
np.linalg.det(A)

4.0

## 5.2 Permutations and cofactores

In [42]:
A = np.array([[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]])
A

array([[ 2, -1,  0,  0],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [ 0,  0, -1,  2]])

##### The pivot formula

In [48]:
from scipy.linalg import lu
p, l, u = lu(A)

In [49]:
u

array([[ 2.        , -1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.5       , -1.        ,  0.        ],
       [ 0.        ,  0.        ,  1.33333333, -1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.25      ]])

In [50]:
np.prod([u.diagonal()]) # the determinant is the product of the pivots

5.0

In [51]:
np.linalg.det(A)

4.999999999999999

##### Example 1

In [53]:
A = np.array([[0,0,1],[0,2,3],[4,5,6]])

In [57]:
p, l, u = lu(A)
p

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),)

In [58]:
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
u

array([[4., 5., 6.],
       [0., 2., 3.],
       [0., 0., 1.]])

In [60]:
p @ A

array([[4., 5., 6.],
       [0., 2., 3.],
       [0., 0., 1.]])

In [66]:
-np.prod([u.diagonal()]) # the determinant

-8.0

In [73]:
np.linalg.det(A)   # the determinant

-7.999999999999998

In [74]:
np.linalg.det(p)* np.linalg.det(A) == np.linalg.det(l)*np.linalg.det(u)

True