## 6.1 Introduction to eigenvalues

In [1]:
import numpy as np

In [2]:
A = np.array([[.8,.3],
              [.2,.7]])

In [3]:
from numpy import linalg

In [4]:
Lambda, x = np.linalg.eig(A)

In [5]:
Lambda  # the eigenvalues

array([1. , 0.5])

In [6]:
x  # the eigenvectors

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [7]:
A @ x[:,0]

array([0.83205029, 0.5547002 ])

In [8]:
Lambda[0]*x[:,0]

array([0.83205029, 0.5547002 ])

In [9]:
A @ x[:,1]

array([-0.35355339,  0.35355339])

In [10]:
Lambda[1]*x[:,1]

array([-0.35355339,  0.35355339])

In [11]:
#Example 2

P = np.array([[.5,.5],[.5,.5]])

In [12]:
e_values, e_vectors= np.linalg.eig(P)

In [13]:
e_values.round()

array([1., 0.])

In [14]:
e_vectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

###### Determinant and trace

In [15]:
A = np.array([[1,3],[2,6]])

In [16]:
from scipy.linalg import lu
p,l,u = lu(A)
u

array([[2., 6.],
       [0., 0.]])

In [17]:
e_values, e_vectors = np.linalg.eig(u)
e_values

array([2., 0.])

In [18]:
e_values, e_vectors = np.linalg.eig(A)
e_values

array([0., 7.])

In [19]:
np.sum(e_values), np.trace(A) 

(7.0, 7)

In [20]:
np.sum(e_values) == np.trace(A) 

True

## 6.2 Diagonalizing a matrix

In [21]:
from sympy import *
A = Matrix([[1,5],[0,6]])

In [22]:
X, LAMBDA = A.diagonalize()

In [23]:
X

Matrix([
[1, 1],
[0, 1]])

In [24]:
X.inv()

Matrix([
[1, -1],
[0,  1]])

In [25]:
LAMBDA

Matrix([
[1, 0],
[0, 6]])

In [26]:
A = np.array([[1,5],[0,6]])
e_values, e_vectors= np.linalg.eig(A)
print("The eigenvalues: ",e_values)

The eigenvalues:  [1. 6.]


In [27]:
print("The eigenvectors: ")
e_vectors

The eigenvectors: 


array([[1.        , 0.70710678],
       [0.        , 0.70710678]])

In [28]:
np.linalg.inv(e_vectors) @ A @ e_vectors

array([[1., 0.],
       [0., 6.]])

In [29]:
# Threfore the two are equal

In [30]:
X @ LAMBDA @ X.inv()

Matrix([
[1, 5],
[0, 6]])

In [31]:
A

array([[1, 5],
       [0, 6]])

In [32]:
# AX = X*LAMBDA

A@X==X@LAMBDA

True

In [33]:
# No diagonalizable matrices

In [34]:
A = Matrix([[1,-1],
            [1,-1]])

try:
    X, LAMBDA = A.diagonalize()
except:
    print('Matrix is not diagonalizable')

Matrix is not diagonalizable


In [35]:
A

Matrix([
[1, -1],
[1, -1]])

In [36]:
try:
    A.inv()
except:
    print('Singular matrix')

Singular matrix


##### Example 2

In [37]:
A = Matrix([[.8,.3],[.2,.7]])

In [38]:
X, LAMBDA = A.diagonalize()
X, LAMBDA

(Matrix([
 [-1.0, 3.0],
 [ 1.0, 2.0]]),
 Matrix([
 [0.5,   0],
 [  0, 1.0]]))

In [39]:
X @ LAMBDA @ X.inv() # this is equal to A

Matrix([
[0.8, 0.3],
[0.2, 0.7]])

In [40]:
# A squared has the same X
A@A

Matrix([
[0.7, 0.45],
[0.3, 0.55]])

In [41]:
A@A== A**2

True

In [42]:
A_squared = A@A
X, LAMBDA = A_squared.diagonalize()
X, LAMBDA # A squared has the same X

(Matrix([
 [-1.0, 3.0],
 [ 1.0, 2.0]]),
 Matrix([
 [0.25,   0],
 [   0, 1.0]]))

In [43]:
# Aproaching the steady state

In [44]:
A**100000

Matrix([
[0.600000000002046, 0.600000000002046],
[0.400000000001364, 0.400000000001364]])

In [45]:
A**1000000000

Matrix([
[0.6, 0.6],
[0.4, 0.4]])

In [46]:
X @ LAMBDA **100 @ X.inv()

Matrix([
[0.6, 0.6],
[0.4, 0.4]])